name: CI
on:
  pull_request:
  push:
  schedule:
  # 2am EST every Saturday
  - cron: '0 7 * * 6'
jobs:
  build_scala2_12:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Scala
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: adopt
    - name: Coursier cache
      uses: coursier/cache-action@v6
    - uses: sbt/setup-sbt@v1
    - name: Build and test
      run: |
        sbt -v clean scalafmtSbtCheck "+ scalafmtCheckAll" "+ test" "+ scripted"
        rm -rf "$HOME/.ivy2/local" || true
        find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
        find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
        find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
        find $HOME/.sbt                              -name "ivydata-*.properties" -delete || true
      shell: bash
