name: CI
on:
  pull_request:
  push:
  schedule:
  # 2am EST every Saturday
  - cron: '0 7 * * 6'
jobs:
  build_scala2_12:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Scala
      uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: zulu
        cache: sbt
    - uses: sbt/setup-sbt@v1
    - name: Build and test
      shell: bash
      run: sbt -v clean scalafmtSbtCheck "+ scalafmtCheckAll" "+ test" "+ scripted"
